/**
 * Configuración de fuentes de datos
 * RSS, APIs y especificación para scraping
 */

import type { DataSource, RssSource, ApiSource } from "@/types/sources";

/**
 * Fuentes RSS - blogs oficiales y changelogs
 * Formato: RSS 2.0, Atom
 */
export const RSS_SOURCES: RssSource[] = [
  {
    id: "nextjs-blog",
    name: "Next.js Blog",
    type: "rss",
    url: "https://nextjs.org/feed.xml",
    technology: "Next.js",
    stack: "nextjs",
    category: "frontend",
    enabled: true,
    fetchInterval: 60,
    versionPattern: /(\d+\.\d+\.\d+)/,
  },
  {
    id: "react-blog",
    name: "React Blog",
    type: "rss",
    url: "https://react.dev/feed.xml",
    technology: "React",
    stack: "react",
    category: "frontend",
    enabled: true,
    fetchInterval: 60,
    versionPattern: /(\d+\.\d+\.\d+)/,
  },
  {
    id: "vercel-blog",
    name: "Vercel Blog",
    type: "rss",
    url: "https://vercel.com/blog/feed.xml",
    technology: "Vercel",
    stack: "vercel",
    category: "devops",
    enabled: true,
    fetchInterval: 120,
  },
  {
    id: "github-blog",
    name: "GitHub Blog",
    type: "rss",
    url: "https://github.blog/feed/",
    technology: "GitHub",
    stack: "github",
    category: "tools",
    enabled: true,
    fetchInterval: 60,
  },
  {
    id: "openai-blog",
    name: "OpenAI Blog",
    type: "rss",
    url: "https://openai.com/blog/rss.xml",
    technology: "OpenAI",
    stack: "openai",
    category: "llms",
    enabled: true,
    fetchInterval: 120,
  },
  {
    id: "anthropic-blog",
    name: "Anthropic Blog",
    type: "rss",
    url: "https://www.anthropic.com/news/rss",
    technology: "Anthropic",
    stack: "claude",
    category: "llms",
    enabled: true,
    fetchInterval: 120,
  },
  {
    id: "huggingface-blog",
    name: "Hugging Face Blog",
    type: "rss",
    url: "https://huggingface.co/blog/feed.xml",
    technology: "Hugging Face",
    stack: "huggingface",
    category: "ai-ml",
    enabled: true,
    fetchInterval: 60,
  },
  {
    id: "pytorch-blog",
    name: "PyTorch Blog",
    type: "rss",
    url: "https://pytorch.org/blog/feed.xml",
    technology: "PyTorch",
    stack: "pytorch",
    category: "ai-ml",
    enabled: true,
    fetchInterval: 120,
  },
  // Más tópicos: lenguajes y runtimes
  {
    id: "rust-blog",
    name: "Rust Blog",
    type: "rss",
    url: "https://blog.rust-lang.org/feed.xml",
    technology: "Rust",
    stack: "rust",
    category: "backend",
    enabled: true,
    fetchInterval: 120,
    versionPattern: /(\d+\.\d+\.\d+)/,
  },
  {
    id: "go-blog",
    name: "Go Blog",
    type: "rss",
    url: "https://go.dev/blog/feed.xml",
    technology: "Go",
    stack: "go",
    category: "backend",
    enabled: true,
    fetchInterval: 120,
    versionPattern: /go(\d+\.\d+)/,
  },
  {
    id: "deno-blog",
    name: "Deno Blog",
    type: "rss",
    url: "https://deno.com/blog/rss",
    technology: "Deno",
    stack: "deno",
    category: "backend",
    enabled: true,
    fetchInterval: 120,
    versionPattern: /(\d+\.\d+\.\d+)/,
  },
  // Frontend: Vue, Svelte, Astro, Nuxt
  {
    id: "vue-blog",
    name: "Vue.js Blog",
    type: "rss",
    url: "https://blog.vuejs.org/feed.xml",
    technology: "Vue",
    stack: "vue",
    category: "frontend",
    enabled: true,
    fetchInterval: 60,
    versionPattern: /(\d+\.\d+\.\d+)/,
  },
  {
    id: "astro-blog",
    name: "Astro Blog",
    type: "rss",
    url: "https://astro.build/blog/feed.xml",
    technology: "Astro",
    stack: "astro",
    category: "frontend",
    enabled: true,
    fetchInterval: 60,
    versionPattern: /(\d+\.\d+\.\d+)/,
  },
  {
    id: "nuxt-blog",
    name: "Nuxt Blog",
    type: "rss",
    url: "https://nuxt.com/feed.xml",
    technology: "Nuxt",
    stack: "nuxt",
    category: "frontend",
    enabled: true,
    fetchInterval: 60,
    versionPattern: /(\d+\.\d+\.\d+)/,
  },
  // DevOps / infra
  {
    id: "cloudflare-blog",
    name: "Cloudflare Blog",
    type: "rss",
    url: "https://blog.cloudflare.com/rss/",
    technology: "Cloudflare",
    stack: "cloudflare",
    category: "devops",
    enabled: true,
    fetchInterval: 120,
  },
  {
    id: "mdn-blog",
    name: "MDN Blog",
    type: "rss",
    url: "https://developer.mozilla.org/en-US/blog/rss.xml",
    technology: "MDN",
    stack: "mdn",
    category: "tools",
    enabled: true,
    fetchInterval: 120,
  },
];

/**
 * Fuentes API - GitHub Releases, npm, etc.
 */
export const API_SOURCES: ApiSource[] = [
  {
    id: "node-releases",
    name: "Node.js Releases",
    type: "api",
    url: "https://nodejs.org/dist/index.json",
    technology: "Node.js",
    stack: "nodejs",
    category: "backend",
    enabled: true,
    fetchInterval: 240,
    dataPath: "", // Array directo
  },
  {
    id: "github-nextjs-releases",
    name: "Next.js GitHub Releases",
    type: "api",
    url: "https://api.github.com/repos/vercel/next.js/releases?per_page=10",
    technology: "Next.js",
    stack: "nextjs",
    category: "frontend",
    enabled: true,
    fetchInterval: 60,
    dataPath: "",
    headers: {
      Accept: "application/vnd.github.v3+json",
      "User-Agent": "TechReleaseNews/1.0",
    },
  },
  {
    id: "github-react-releases",
    name: "React GitHub Releases",
    type: "api",
    url: "https://api.github.com/repos/facebook/react/releases?per_page=10",
    technology: "React",
    stack: "react",
    category: "frontend",
    enabled: true,
    fetchInterval: 60,
    dataPath: "",
    headers: {
      Accept: "application/vnd.github.v3+json",
      "User-Agent": "TechReleaseNews/1.0",
    },
  },
  {
    id: "github-vue-releases",
    name: "Vue GitHub Releases",
    type: "api",
    url: "https://api.github.com/repos/vuejs/core/releases?per_page=10",
    technology: "Vue",
    stack: "vue",
    category: "frontend",
    enabled: true,
    fetchInterval: 60,
    dataPath: "",
    headers: {
      Accept: "application/vnd.github.v3+json",
      "User-Agent": "TechReleaseNews/1.0",
    },
  },
  {
    id: "github-svelte-releases",
    name: "Svelte GitHub Releases",
    type: "api",
    url: "https://api.github.com/repos/sveltejs/svelte/releases?per_page=10",
    technology: "Svelte",
    stack: "svelte",
    category: "frontend",
    enabled: true,
    fetchInterval: 60,
    dataPath: "",
    headers: {
      Accept: "application/vnd.github.v3+json",
      "User-Agent": "TechReleaseNews/1.0",
    },
  },
  {
    id: "github-vite-releases",
    name: "Vite GitHub Releases",
    type: "api",
    url: "https://api.github.com/repos/vitejs/vite/releases?per_page=10",
    technology: "Vite",
    stack: "vite",
    category: "frontend",
    enabled: true,
    fetchInterval: 60,
    dataPath: "",
    headers: {
      Accept: "application/vnd.github.v3+json",
      "User-Agent": "TechReleaseNews/1.0",
    },
  },
  {
    id: "github-typescript-releases",
    name: "TypeScript GitHub Releases",
    type: "api",
    url: "https://api.github.com/repos/microsoft/TypeScript/releases?per_page=10",
    technology: "TypeScript",
    stack: "typescript",
    category: "tools",
    enabled: true,
    fetchInterval: 60,
    dataPath: "",
    headers: {
      Accept: "application/vnd.github.v3+json",
      "User-Agent": "TechReleaseNews/1.0",
    },
  },
  {
    id: "github-tailwind-releases",
    name: "Tailwind CSS GitHub Releases",
    type: "api",
    url: "https://api.github.com/repos/tailwindlabs/tailwindcss/releases?per_page=10",
    technology: "Tailwind CSS",
    stack: "tailwind",
    category: "frontend",
    enabled: true,
    fetchInterval: 60,
    dataPath: "",
    headers: {
      Accept: "application/vnd.github.v3+json",
      "User-Agent": "TechReleaseNews/1.0",
    },
  },
  {
    id: "github-astro-releases",
    name: "Astro GitHub Releases",
    type: "api",
    url: "https://api.github.com/repos/withastro/astro/releases?per_page=10",
    technology: "Astro",
    stack: "astro",
    category: "frontend",
    enabled: true,
    fetchInterval: 60,
    dataPath: "",
    headers: {
      Accept: "application/vnd.github.v3+json",
      "User-Agent": "TechReleaseNews/1.0",
    },
  },
  {
    id: "github-nuxt-releases",
    name: "Nuxt GitHub Releases",
    type: "api",
    url: "https://api.github.com/repos/nuxt/nuxt/releases?per_page=10",
    technology: "Nuxt",
    stack: "nuxt",
    category: "frontend",
    enabled: true,
    fetchInterval: 60,
    dataPath: "",
    headers: {
      Accept: "application/vnd.github.v3+json",
      "User-Agent": "TechReleaseNews/1.0",
    },
  },
  {
    id: "github-deno-releases",
    name: "Deno GitHub Releases",
    type: "api",
    url: "https://api.github.com/repos/denoland/deno/releases?per_page=10",
    technology: "Deno",
    stack: "deno",
    category: "backend",
    enabled: true,
    fetchInterval: 60,
    dataPath: "",
    headers: {
      Accept: "application/vnd.github.v3+json",
      "User-Agent": "TechReleaseNews/1.0",
    },
  },
  {
    id: "github-remix-releases",
    name: "Remix GitHub Releases",
    type: "api",
    url: "https://api.github.com/repos/remix-run/remix/releases?per_page=10",
    technology: "Remix",
    stack: "remix",
    category: "frontend",
    enabled: true,
    fetchInterval: 60,
    dataPath: "",
    headers: {
      Accept: "application/vnd.github.v3+json",
      "User-Agent": "TechReleaseNews/1.0",
    },
  },
];

/**
 * Especificación de fuentes para Scraping
 * Requiere implementación con Puppeteer/Playwright - solo especificación
 */
export const SCRAPING_SOURCES_SPEC = [
  {
    id: "typescript-release-notes",
    name: "TypeScript Release Notes",
    url: "https://www.typescriptlang.org/docs/handbook/release-notes/overview.html",
    technology: "TypeScript",
    stack: "typescript",
    category: "tools",
    strategy: "static" as const,
    selectors: {
      items: "article h2",
      title: "h2",
      link: "a",
    },
  },
  {
    id: "tailwind-releases",
    name: "Tailwind CSS Releases",
    url: "https://github.com/tailwindlabs/tailwindcss/releases",
    technology: "Tailwind CSS",
    stack: "tailwind",
    category: "frontend",
    strategy: "static" as const,
    note: "GitHub releases page - preferir API si hay rate limit disponible",
  },
];

/**
 * Todas las fuentes activas
 */
export function getActiveSources(): DataSource[] {
  return [
    ...RSS_SOURCES.filter((s) => s.enabled !== false),
    ...API_SOURCES.filter((s) => s.enabled !== false),
  ];
}
