/**
 * Configuración de fuentes de datos
 * RSS, APIs y especificación para scraping
 */

import type { DataSource, RssSource, ApiSource } from "@/types/sources";

/**
 * Fuentes RSS - blogs oficiales y changelogs
 * Formato: RSS 2.0, Atom
 */
export const RSS_SOURCES: RssSource[] = [
  {
    id: "nextjs-blog",
    name: "Next.js Blog",
    type: "rss",
    url: "https://nextjs.org/feed.xml",
    technology: "Next.js",
    npmPackage: "next",
    stack: "nextjs",
    category: "frontend",
    enabled: false, // Sin feed RSS — cubierto por github-nextjs-releases
    fetchInterval: 60,
    versionPattern: /(\d+\.\d+\.\d+)/,
  },
  {
    id: "react-blog",
    name: "React Blog",
    type: "rss",
    url: "https://react.dev/feed.xml",
    technology: "React",
    npmPackage: "react",
    stack: "react",
    category: "frontend",
    enabled: true,
    fetchInterval: 60,
    versionPattern: /(\d+\.\d+\.\d+)/,
  },
  {
    id: "vercel-blog",
    name: "Vercel Blog",
    type: "rss",
    url: "https://vercel.com/blog/feed.xml",
    technology: "Vercel",
    stack: "vercel",
    category: "devops",
    enabled: false, // No relevante para el proyecto
    fetchInterval: 120,
  },
  {
    id: "github-blog",
    name: "GitHub Blog",
    type: "rss",
    url: "https://github.blog/feed/",
    technology: "GitHub",
    stack: "github",
    category: "tools",
    enabled: true,
    fetchInterval: 60,
  },
  {
    id: "openai-blog",
    name: "OpenAI Blog",
    type: "rss",
    url: "https://openai.com/blog/rss.xml",
    technology: "OpenAI",
    stack: "openai",
    category: "llms",
    enabled: true,
    fetchInterval: 120,
  },
  {
    id: "anthropic-blog",
    name: "Anthropic Blog",
    type: "rss",
    url: "https://www.anthropic.com/news/rss",
    technology: "Anthropic",
    stack: "claude",
    category: "llms",
    enabled: false, // Sin feed RSS — cubierto por SDK API sources
    fetchInterval: 120,
  },
  {
    id: "huggingface-blog",
    name: "Hugging Face Blog",
    type: "rss",
    url: "https://huggingface.co/blog/feed.xml",
    technology: "Hugging Face",
    stack: "huggingface",
    category: "ai-ml",
    enabled: true,
    fetchInterval: 60,
  },
  {
    id: "pytorch-blog",
    name: "PyTorch Blog",
    type: "rss",
    url: "https://pytorch.org/blog/feed.xml",
    technology: "PyTorch",
    stack: "pytorch",
    category: "ai-ml",
    enabled: true,
    fetchInterval: 120,
  },
  // Más tópicos: lenguajes y runtimes
  {
    id: "rust-blog",
    name: "Rust Blog",
    type: "rss",
    url: "https://blog.rust-lang.org/feed.xml",
    technology: "Rust",
    stack: "rust",
    category: "backend",
    enabled: true,
    fetchInterval: 120,
    versionPattern: /(\d+\.\d+\.\d+)/,
  },
  {
    id: "go-blog",
    name: "Go Blog",
    type: "rss",
    url: "https://go.dev/blog/feed.atom",
    technology: "Go",
    stack: "go",
    category: "backend",
    enabled: true,
    fetchInterval: 120,
    versionPattern: /go(\d+\.\d+)/,
  },
  {
    id: "deno-blog",
    name: "Deno Blog",
    type: "rss",
    url: "https://deno.com/feed",
    technology: "Deno",
    stack: "deno",
    category: "backend",
    enabled: true,
    fetchInterval: 120,
    versionPattern: /(\d+\.\d+\.\d+)/,
  },
  // Frontend: Vue, Svelte, Astro, Nuxt
  {
    id: "vue-blog",
    name: "Vue.js Blog",
    type: "rss",
    url: "https://blog.vuejs.org/feed.rss",
    technology: "Vue",
    npmPackage: "vue",
    stack: "vue",
    category: "frontend",
    enabled: true,
    fetchInterval: 60,
    versionPattern: /(\d+\.\d+\.\d+)/,
  },
  {
    id: "astro-blog",
    name: "Astro Blog",
    type: "rss",
    url: "https://astro.build/rss.xml",
    technology: "Astro",
    npmPackage: "astro",
    stack: "astro",
    category: "frontend",
    enabled: true,
    fetchInterval: 60,
    versionPattern: /(\d+\.\d+\.\d+)/,
  },
  {
    id: "nuxt-blog",
    name: "Nuxt Blog",
    type: "rss",
    url: "https://nuxt.com/blog/rss.xml",
    technology: "Nuxt",
    npmPackage: "nuxt",
    stack: "nuxt",
    category: "frontend",
    enabled: true,
    fetchInterval: 60,
    versionPattern: /(\d+\.\d+\.\d+)/,
  },
  // DevOps / infra
  {
    id: "cloudflare-blog",
    name: "Cloudflare Blog",
    type: "rss",
    url: "https://blog.cloudflare.com/rss/",
    technology: "Cloudflare",
    stack: "cloudflare",
    category: "devops",
    enabled: true,
    fetchInterval: 120,
  },
  {
    id: "mdn-blog",
    name: "MDN Blog",
    type: "rss",
    url: "https://developer.mozilla.org/en-US/blog/rss.xml",
    technology: "MDN",
    stack: "mdn",
    category: "tools",
    enabled: true,
    fetchInterval: 120,
  },
  // AI/ML Frameworks
  {
    id: "tensorflow-blog",
    name: "TensorFlow Blog",
    type: "rss",
    url: "https://blog.tensorflow.org/feeds/posts/default?alt=rss",
    technology: "TensorFlow",
    stack: "tensorflow",
    category: "ai-ml",
    enabled: true,
    fetchInterval: 120,
  },
  {
    id: "langchain-blog",
    name: "LangChain Blog",
    type: "rss",
    url: "https://blog.langchain.dev/rss/",
    technology: "LangChain",
    stack: "langchain",
    category: "ai-ml",
    enabled: true,
    fetchInterval: 120,
  },
  // Otros LLMs
  {
    id: "google-ai-blog",
    name: "Google AI Blog",
    type: "rss",
    url: "https://blog.google/technology/ai/rss/",
    technology: "Google AI",
    stack: "gemini",
    category: "llms",
    enabled: true,
    fetchInterval: 120,
  },
  {
    id: "mistral-blog",
    name: "Mistral AI Blog",
    type: "rss",
    url: "https://mistral.ai/feed.xml",
    technology: "Mistral AI",
    stack: "mistral",
    category: "llms",
    enabled: false, // Sin feed RSS disponible
    fetchInterval: 120,
  },
  {
    id: "meta-ai-blog",
    name: "Meta AI Research Blog",
    type: "rss",
    url: "https://engineering.fb.com/category/ai-research/feed/",
    technology: "Meta AI",
    stack: "llama",
    category: "llms",
    enabled: true,
    fetchInterval: 120,
  },
  {
    id: "cohere-blog",
    name: "Cohere Blog",
    type: "rss",
    url: "https://cohere.com/blog/rss",
    technology: "Cohere",
    stack: "cohere",
    category: "llms",
    enabled: false, // Feed no es RSS válido
    fetchInterval: 120,
  },
];

/**
 * Fuentes API - GitHub Releases, npm, etc.
 */
export const API_SOURCES: ApiSource[] = [
  {
    id: "node-releases",
    name: "Node.js Releases",
    type: "api",
    url: "https://nodejs.org/dist/index.json",
    technology: "Node.js",
    npmPackage: "node",
    stack: "nodejs",
    category: "backend",
    enabled: true,
    fetchInterval: 240,
    dataPath: "", // Array directo
  },
  {
    id: "github-nextjs-releases",
    name: "Next.js GitHub Releases",
    type: "api",
    url: "https://api.github.com/repos/vercel/next.js/releases?per_page=10",
    technology: "Next.js",
    npmPackage: "next",
    stack: "nextjs",
    category: "frontend",
    enabled: true,
    fetchInterval: 60,
    dataPath: "",
    headers: {
      Accept: "application/vnd.github.v3+json",
      "User-Agent": "TechReleaseNews/1.0",
    },
  },
  {
    id: "github-react-releases",
    name: "React GitHub Releases",
    type: "api",
    url: "https://api.github.com/repos/facebook/react/releases?per_page=10",
    technology: "React",
    npmPackage: "react",
    stack: "react",
    category: "frontend",
    enabled: true,
    fetchInterval: 60,
    dataPath: "",
    headers: {
      Accept: "application/vnd.github.v3+json",
      "User-Agent": "TechReleaseNews/1.0",
    },
  },
  {
    id: "github-vue-releases",
    name: "Vue GitHub Releases",
    type: "api",
    url: "https://api.github.com/repos/vuejs/core/releases?per_page=10",
    technology: "Vue",
    npmPackage: "vue",
    stack: "vue",
    category: "frontend",
    enabled: true,
    fetchInterval: 60,
    dataPath: "",
    headers: {
      Accept: "application/vnd.github.v3+json",
      "User-Agent": "TechReleaseNews/1.0",
    },
  },
  {
    id: "github-svelte-releases",
    name: "Svelte GitHub Releases",
    type: "api",
    url: "https://api.github.com/repos/sveltejs/svelte/releases?per_page=10",
    technology: "Svelte",
    npmPackage: "svelte",
    stack: "svelte",
    category: "frontend",
    enabled: true,
    fetchInterval: 60,
    dataPath: "",
    headers: {
      Accept: "application/vnd.github.v3+json",
      "User-Agent": "TechReleaseNews/1.0",
    },
  },
  {
    id: "github-vite-releases",
    name: "Vite GitHub Releases",
    type: "api",
    url: "https://api.github.com/repos/vitejs/vite/releases?per_page=10",
    technology: "Vite",
    npmPackage: "vite",
    stack: "vite",
    category: "frontend",
    enabled: true,
    fetchInterval: 60,
    dataPath: "",
    headers: {
      Accept: "application/vnd.github.v3+json",
      "User-Agent": "TechReleaseNews/1.0",
    },
  },
  {
    id: "github-typescript-releases",
    name: "TypeScript GitHub Releases",
    type: "api",
    url: "https://api.github.com/repos/microsoft/TypeScript/releases?per_page=10",
    technology: "TypeScript",
    npmPackage: "typescript",
    stack: "typescript",
    category: "tools",
    enabled: true,
    fetchInterval: 60,
    dataPath: "",
    headers: {
      Accept: "application/vnd.github.v3+json",
      "User-Agent": "TechReleaseNews/1.0",
    },
  },
  {
    id: "github-tailwind-releases",
    name: "Tailwind CSS GitHub Releases",
    type: "api",
    url: "https://api.github.com/repos/tailwindlabs/tailwindcss/releases?per_page=10",
    technology: "Tailwind CSS",
    npmPackage: "tailwindcss",
    stack: "tailwind",
    category: "frontend",
    enabled: true,
    fetchInterval: 60,
    dataPath: "",
    headers: {
      Accept: "application/vnd.github.v3+json",
      "User-Agent": "TechReleaseNews/1.0",
    },
  },
  {
    id: "github-astro-releases",
    name: "Astro GitHub Releases",
    type: "api",
    url: "https://api.github.com/repos/withastro/astro/releases?per_page=10",
    technology: "Astro",
    npmPackage: "astro",
    stack: "astro",
    category: "frontend",
    enabled: true,
    fetchInterval: 60,
    dataPath: "",
    headers: {
      Accept: "application/vnd.github.v3+json",
      "User-Agent": "TechReleaseNews/1.0",
    },
  },
  {
    id: "github-nuxt-releases",
    name: "Nuxt GitHub Releases",
    type: "api",
    url: "https://api.github.com/repos/nuxt/nuxt/releases?per_page=10",
    technology: "Nuxt",
    npmPackage: "nuxt",
    stack: "nuxt",
    category: "frontend",
    enabled: true,
    fetchInterval: 60,
    dataPath: "",
    headers: {
      Accept: "application/vnd.github.v3+json",
      "User-Agent": "TechReleaseNews/1.0",
    },
  },
  {
    id: "github-deno-releases",
    name: "Deno GitHub Releases",
    type: "api",
    url: "https://api.github.com/repos/denoland/deno/releases?per_page=10",
    technology: "Deno",
    stack: "deno",
    category: "backend",
    enabled: true,
    fetchInterval: 60,
    dataPath: "",
    headers: {
      Accept: "application/vnd.github.v3+json",
      "User-Agent": "TechReleaseNews/1.0",
    },
  },
  {
    id: "github-remix-releases",
    name: "Remix GitHub Releases",
    type: "api",
    url: "https://api.github.com/repos/remix-run/remix/releases?per_page=10",
    technology: "Remix",
    npmPackage: "@remix-run/react",
    stack: "remix",
    category: "frontend",
    enabled: true,
    fetchInterval: 60,
    dataPath: "",
    headers: {
      Accept: "application/vnd.github.v3+json",
      "User-Agent": "TechReleaseNews/1.0",
    },
  },
  // Claude API/SDK Releases
  {
    id: "github-anthropic-sdk-python",
    name: "Anthropic SDK Python",
    type: "api",
    url: "https://api.github.com/repos/anthropics/anthropic-sdk-python/releases?per_page=10",
    technology: "Anthropic SDK Python",
    npmPackage: "anthropic",
    stack: "claude",
    category: "llms",
    enabled: true,
    fetchInterval: 120,
    dataPath: "",
    headers: {
      Accept: "application/vnd.github.v3+json",
      "User-Agent": "TechReleaseNews/1.0",
    },
  },
  {
    id: "github-anthropic-sdk-typescript",
    name: "Anthropic SDK TypeScript",
    type: "api",
    url: "https://api.github.com/repos/anthropics/anthropic-sdk-typescript/releases?per_page=10",
    technology: "Anthropic SDK TypeScript",
    npmPackage: "@anthropic-ai/sdk",
    stack: "claude",
    category: "llms",
    enabled: true,
    fetchInterval: 120,
    dataPath: "",
    headers: {
      Accept: "application/vnd.github.v3+json",
      "User-Agent": "TechReleaseNews/1.0",
    },
  },
  {
    id: "github-claude-code-releases",
    name: "Claude Code Releases",
    type: "api",
    url: "https://api.github.com/repos/anthropics/claude-code/releases?per_page=10",
    technology: "Claude Code",
    stack: "claude",
    category: "llms",
    enabled: true,
    fetchInterval: 120,
    dataPath: "",
    headers: {
      Accept: "application/vnd.github.v3+json",
      "User-Agent": "TechReleaseNews/1.0",
    },
  },
  // AI/ML Frameworks
  {
    id: "github-langchain-releases",
    name: "LangChain Python Releases",
    type: "api",
    url: "https://api.github.com/repos/langchain-ai/langchain/releases?per_page=10",
    technology: "LangChain",
    npmPackage: "langchain",
    stack: "langchain",
    category: "ai-ml",
    enabled: true,
    fetchInterval: 120,
    dataPath: "",
    headers: {
      Accept: "application/vnd.github.v3+json",
      "User-Agent": "TechReleaseNews/1.0",
    },
  },
  {
    id: "github-llamaindex-releases",
    name: "LlamaIndex Releases",
    type: "api",
    url: "https://api.github.com/repos/run-llama/llama_index/releases?per_page=10",
    technology: "LlamaIndex",
    stack: "llamaindex",
    category: "ai-ml",
    enabled: true,
    fetchInterval: 120,
    dataPath: "",
    headers: {
      Accept: "application/vnd.github.v3+json",
      "User-Agent": "TechReleaseNews/1.0",
    },
  },
  {
    id: "github-ollama-releases",
    name: "Ollama Releases",
    type: "api",
    url: "https://api.github.com/repos/ollama/ollama/releases?per_page=10",
    technology: "Ollama",
    stack: "ollama",
    category: "ai-ml",
    enabled: true,
    fetchInterval: 120,
    dataPath: "",
    headers: {
      Accept: "application/vnd.github.v3+json",
      "User-Agent": "TechReleaseNews/1.0",
    },
  },
  {
    id: "github-transformers-releases",
    name: "Transformers Releases",
    type: "api",
    url: "https://api.github.com/repos/huggingface/transformers/releases?per_page=10",
    technology: "Transformers",
    npmPackage: "@huggingface/transformers",
    stack: "huggingface",
    category: "ai-ml",
    enabled: true,
    fetchInterval: 120,
    dataPath: "",
    headers: {
      Accept: "application/vnd.github.v3+json",
      "User-Agent": "TechReleaseNews/1.0",
    },
  },
];

/**
 * Especificación de fuentes para Scraping
 * Requiere implementación con Puppeteer/Playwright - solo especificación
 */
export const SCRAPING_SOURCES_SPEC = [
  {
    id: "typescript-release-notes",
    name: "TypeScript Release Notes",
    url: "https://www.typescriptlang.org/docs/handbook/release-notes/overview.html",
    technology: "TypeScript",
    stack: "typescript",
    category: "tools",
    strategy: "static" as const,
    selectors: {
      items: "article h2",
      title: "h2",
      link: "a",
    },
  },
  {
    id: "tailwind-releases",
    name: "Tailwind CSS Releases",
    url: "https://github.com/tailwindlabs/tailwindcss/releases",
    technology: "Tailwind CSS",
    stack: "tailwind",
    category: "frontend",
    strategy: "static" as const,
    note: "GitHub releases page - preferir API si hay rate limit disponible",
  },
];

/**
 * Todas las fuentes activas
 */
export function getActiveSources(): DataSource[] {
  return [
    ...RSS_SOURCES.filter((s) => s.enabled !== false),
    ...API_SOURCES.filter((s) => s.enabled !== false),
  ];
}
